// THIS FILE IS GENERATED BY CODE GENERATOR. DO NOT CHANGE MANUALLY.
/* tslint:disable */
/* eslint-disable */
<%_ for (const key of Object.keys(refs)) { _%>
import <%= refs[key].name %> from './<%= refs[key].name %>'
<%_ } _%>

export default interface <%= className %> {
<%_ for (const key of Object.keys(schema)) { _%>
  <%= schema[key].required ? schema[key].key : schema[key].key+'?' %>: <%= schema[key].tstype%>
<%_ } _%>
}
