// THIS FILE IS GENERATED BY CODE GENERATOR. DO NOT CHANGE MANUALLY.
/* tslint:disable */
/* eslint-disable */
<%_ for (const ref of refs) { _%>
import <%= ref.name %> from './<%= ref.name %>'
<%_ } _%>

export default interface <%= className %> {
<%_ for (const schema of Object.values(schemas)) { _%>
  <%= schema.required ? schema.key : schema.key+'?' %>: <%= schema.tstype%>
<%_ } _%>
}
