// THIS FILE IS GENERATED BY CODE GENERATOR. DO NOT CHANGE MANUALLY.
/* tslint:disable */
/* eslint-disable */
<%_ for (const key of Object.keys(classes)) { _%>
export { default as <%= classes[key].name %> } from './<%= classes[key].name %>'
<%_ } _%>
